

arrayOfProducts = [
    { id: 1, name: "NeoQled", price: 500, description: "High Quality TV", category: "TV", pics: ["../media/img/categoryTV/1a.jpg", "../media/img/categoryTV/1b.jpg"] },
    { id: 2, name: "LG UHD TV", price: 600, description: "High Quality TV", category: "TV", pics: ["../media/img/categoryTV/2a.jpg", "../media/img/categoryTV/2b.jpg"] },
    { id: 3, name: "SAMSUNG", price: 700, description: "High Quality TV", category: "TV", pics: ["../media/img/categoryTV/3a.jpg", "../media/img/categoryTV/3b.jpg"] },
    { id: 4, name: "SAMSUNG", price: 800, description: "High Quality TV", category: "TV", pics: ["../media/img/categoryTV/4a.jpg", "../media/img/categoryTV/4b.jpg"] },
    { id: 5, name: "LG UHD TV", price: 500, description: "High Quality TV", category: "TV", pics: ["../media/img/categoryTV/5a.jpg", "../media/img/categoryTV/5b.jpg"] },
    { id: 6, name: "LG TV", price: 450, description: "High Quality TV", category: "TV", pics: ["../media/img/categoryTV/6a.jpg", "../media/img/categoryTV/6b.jpg"] },
    { id: 7, name: "PANASONIC", price: 700, description: "High Quality TV", category: "TV", pics: ["../media/img/categoryTV/7a.png", "../media/img/categoryTV/7b.jpg"] },
    { id: 8, name: "LG OLED", price: 600, description: "High Quality TV", category: "TV", pics: ["../media/img/categoryTV/8a.jpg", "../media/img/categoryTV/8b.jpg"] },
    { id: 9, name: "LG UHD", price: 500, description: "High Quality TV", category: "TV", pics: ["../media/img/categoryTV/9a.jpg", "../media/img/categoryTV/9b.jpg"] },
    { id: 10, name: "LG UHD", price: 700, description: "High Quality TV", category: "TV", pics: ["../media/img/categoryTV/10a.jpg", "../media/img/categoryTV/10b.jpg"] },
    { id: 11, name: "CRYSTAL UHD", price: 900, description: "High Quality TV", category: "TV", pics: ["../media/img/categoryTV/11a.jpg", "../media/img/categoryTV/11b.jpg"] },
    { id: 12, name: "NEO QLED", price: 800, description: "High Quality TV", category: "TV", pics: ["../media/img/categoryTV/12a.jpg", "../media/img/categoryTV/12b.jpg"] },
    { id: 13, name: "CRYSTAL UHD", price: 500, description: "High Quality TV", category: "TV", pics: ["../media/img/categoryTV/13a.jpg", "../media/img/categoryTV/13b.jpg"] },
    { id: 14, name: "AQUOS", price: 600, description: "High Quality TV", category: "TV", pics: ["../media/img/categoryTV/14a.jpg", "../media/img/categoryTV/14b.jpg"] },
    { id: 15, name: "LG OLED", price: 400, description: "High Quality TV", category: "TV", pics: ["../media/img/categoryTV/15a.jpg", "../media/img/categoryTV/15b.jpg"] },
    { id: 16, name: "SAMSUNG", price: 800, description: "High Quality TV", category: "TV", pics: ["../media/img/categoryTV/16a.jpg", "../media/img/categoryTV/16b.jpg"] },
    { id: 17, name: "LG NANO CELL", price: 700, description: "High Quality TV", category: "TV", pics: ["../media/img/categoryTV/17a.jpg", "../media/img/categoryTV/17b.jpg"] },
    { id: 18, name: "HISENSE", price: 600, description: "High Quality TV", category: "TV", pics: ["../media/img/categoryTV/18a.jpg", "../media/img/categoryTV/18b.jpg"] },
    { id: 19, name: "LG NANO CELL", price: 900, description: "High Quality TV", category: "TV", pics: ["../media/img/categoryTV/19a.jpg", "../media/img/categoryTV/19b.jpg"] },
    { id: 20, name: "HISENSE", price: 700, description: "High Quality TV", category: "TV", pics: ["../media/img/categoryTV/20a.jpg", "../media/img/categoryTV/20b.jpg"] },
    { id: 21, name: "HP", price: 999, description: "i7", category: "Laptops", pics: ["../media/img/categoryLaptops/21a.jpg", "../media/img/categoryLaptops/21b.jpg"] },
    { id: 22, name: "HP", price: 1099, description: "i7", category: "Laptops", pics: ["../media/img/categoryLaptops/22a.jpg", "../media/img/categoryLaptops/22b.jpg"] },
    { id: 23, name: "TOSHIBA", price: 1199, description: "i5", category: "Laptops", pics: ["../media/img/categoryLaptops/23a.jpg", "../media/img/categoryLaptops/23b.jpg"] },
    { id: 24, name: "SAMSUNG", price: 899, description: "i7", category: "Laptops", pics: ["../media/img/categoryLaptops/24a.jpg", "../media/img/categoryLaptops/24b.jpg"] },
    { id: 25, name: "HP", price: 899, description: "i5", category: "Laptops", pics: ["../media/img/categoryLaptops/25a.jpg", "../media/img/categoryLaptops/25b.jpg"] },
    { id: 26, name: "TOSHIBA", price: 999, description: "i7", category: "Laptops", pics: ["../media/img/categoryLaptops/26a.jpg", "../media/img/categoryLaptops/26b.jpg"] },
    { id: 27, name: "SAMSUNG", price: 1199, description: "i7", category: "Laptops", pics: ["../media/img/categoryLaptops/27a.jpg", "../media/img/categoryLaptops/27b.jpg"] },
    { id: 28, name: "SAMSUNG", price: 899, description: "i7", category: "Laptops", pics: ["../media/img/categoryLaptops/28a.jpg", "../media/img/categoryLaptops/28b.jpg"] },
    { id: 29, name: "HP", price: 899, description: "i3", category: "Laptops", pics: ["../media/img/categoryLaptops/29a.jpg", "../media/img/categoryLaptops/29b.jpg"] },
    { id: 30, name: "HP", price: 799, description: "i7", category: "Laptops", pics: ["../media/img/categoryLaptops/30a.jpg", "../media/img/categoryLaptops/30b.jpg"] },
    { id: 31, name: "SAMSUNG", price: 1099, description: "i7", category: "Laptops", pics: ["../media/img/categoryLaptops/31a.jpg", "../media/img/categoryLaptops/31b.jpg"] },
    { id: 32, name: "TOSHIBA", price: 999, description: "i5", category: "Laptops", pics: ["../media/img/categoryLaptops/32a.jpg", "../media/img/categoryLaptops/32b.jpg"] },
    { id: 33, name: "HP", price: 999, description: "i7", category: "Laptops", pics: ["../media/img/categoryLaptops/33a.jpg", "../media/img/categoryLaptops/33b.jpg"] },
    { id: 34, name: "SAMSUNG", price: 899, description: "i7", category: "Laptops", pics: ["../media/img/categoryLaptops/34a.jpg", "../media/img/categoryLaptops/34b.jpg"] },
    { id: 35, name: "HP", price: 1099, description: "i3", category: "Laptops", pics: ["../media/img/categoryLaptops/35a.jpg", "../media/img/categoryLaptops/35b.jpg"] },
    { id: 36, name: "TOSHIBA", price: 1199, description: "i7", category: "Laptops", pics: ["../media/img/categoryLaptops/36a.jpg", "../media/img/categoryLaptops/36b.jpg"] },
    { id: 37, name: "HP", price: 799, description: "i7", category: "Laptops", pics: ["../media/img/categoryLaptops/37a.jpg", "../media/img/categoryLaptops/37b.jpg"] },
    { id: 38, name: "SAMSUNG", price: 999, description: "i7", category: "Laptops", pics: ["../media/img/categoryLaptops/38a.jpg", "../media/img/categoryLaptops/38b.jpg"] },
    { id: 39, name: "TOSHIBA", price: 799, description: "i7", category: "Laptops", pics: ["../media/img/categoryLaptops/39a.jpg", "../media/img/categoryLaptops/39b.jpg"] },
    { id: 40, name: "HP", price: 899, description: "i3", category: "Laptops", pics: ["../media/img/categoryLaptops/40a.jpg", "../media/img/categoryLaptops/40b.jpg"] },
    { id: 41, name: "SONY", price: 99, description: "For a Clean Style", category: "Shaving", pics: ["../media/img/categoryHair/shaving/41a.png", "../media/img/categoryHair/shaving/41b.jpg"] },
    { id: 42, name: "SANGYONG", price: 49, description: "For a Clean Style", category: "Shaving", pics: ["../media/img/categoryHair/shaving/42a.jpg", "../media/img/categoryHair/shaving/42b.jpg"] },
    { id: 43, name: "BRAUN", price: 59, description: "For a Clean Style", category: "Shaving", pics: ["../media/img/categoryHair/shaving/43a.jpg", "../media/img/categoryHair/shaving/43b.jpg"] },
    { id: 44, name: "PHILIPS", price: 79, description: "For a Clean Style", category: "Shaving", pics: ["../media/img/categoryHair/shaving/44a.jpg", "../media/img/categoryHair/shaving/44b.png"] },
    { id: 45, name: "PHILIPS", price: 89, description: "For a Clean Style", category: "Shaving", pics: ["../media/img/categoryHair/shaving/45a.jpg", "../media/img/categoryHair/shaving/45b.png"] },
    { id: 46, name: "BAYBYLISS", price: 99, description: "For a Straight Hair", category: "hairStraightener", pics: ["../media/img/categoryHair/hairStraightener/46a.png", "../media/img/categoryHair/hairStraightener/46b.png"] },
    { id: 47, name: "SONY", price: 89, description: "For a Straight Hair", category: "hairStraightener", pics: ["../media/img/categoryHair/hairStraightener/47a.jpg", "../media/img/categoryHair/hairStraightener/47b.jpg"] },
    { id: 48, name: "SHARP", price: 79, description: "For a Straight Hair", category: "hairStraightener", pics: ["../media/img/categoryHair/hairStraightener/48a.png", "../media/img/categoryHair/hairStraightener/48b.jpg"] },
    { id: 49, name: "SAMSUNG", price: 89, description: "For a Straight Hair", category: "hairStraightener", pics: ["../media/img/categoryHair/hairStraightener/49a.png", "../media/img/categoryHair/hairStraightener/49b.png"] },
    { id: 50, name: "BAYBYLISS", price: 69, description: "For a Straight Hair", category: "hairStraightener", pics: ["../media/img/categoryHair/hairStraightener/50a.jpg", "../media/img/categoryHair/hairStraightener/50b.jpg"] },
    { id: 51, name: "PANASONIC", price: 99, description: "For a Fresh Cut", category: "trimers", pics: ["../media/img/categoryHair/trimers/51a.jpg", "../media/img/categoryHair/trimers/51b.jpg"] },
    { id: 52, name: "PANASONIC", price: 89, description: "For a Fresh Cut", category: "trimers", pics: ["../media/img/categoryHair/trimers/52a.jpg", "../media/img/categoryHair/trimers/52b.jpg"] },
    { id: 53, name: "PHILIPS", price: 99, description: "For a Fresh Cut", category: "trimers", pics: ["../media/img/categoryHair/trimers/53a.jpg", "../media/img/categoryHair/trimers/53b.jpg"] },
    { id: 54, name: "WAHL", price: 69, description: "For a Fresh Cut", category: "trimers", pics: ["../media/img/categoryHair/trimers/54a.jpg", "../media/img/categoryHair/trimers/54b.jpg"] },
    { id: 55, name: "BABYLISS", price: 79, description: "For a Fresh Cut", category: "trimers", pics: ["../media/img/categoryHair/trimers/55a.jpg", "../media/img/categoryHair/trimers/55b.png"] },
    { id: 56, name: "PANUKS", price: 89, description: "For a Soft Touch", category: "hairDryer", pics: ["../media/img/categoryHair/hairDryer/56a.jpg", "../media/img/categoryHair/hairDryer/56b.jpg"] },
    { id: 57, name: "BABYLISS", price: 99, description: "For a Soft Touch", category: "hairDryer", pics: ["../media/img/categoryHair/hairDryer/57a.jpg", "../media/img/categoryHair/hairDryer/57b.png"] },
    { id: 58, name: "SONY", price: 79, description: "For a Soft Touch", category: "hairDryer", pics: ["../media/img/categoryHair/hairDryer/58a.png", "../media/img/categoryHair/hairDryer/58b.jpg"] },
    { id: 59, name: "PHILIPS", price: 89, description: "For a Soft Touch", category: "hairDryer", pics: ["../media/img/categoryHair/hairDryer/59a.jpg", "../media/img/categoryHair/hairDryer/59b.jpg"] },
    { id: 60, name: "BABYLISS", price: 79, description: "For a Soft Touch", category: "hairDryer", pics: ["../media/img/categoryHair/hairDryer/60a.jpg", "../media/img/categoryHair/hairDryer/60b.png"] },
    { id: 61, name: "ELECTRA", price: 399, description: "For a Hot Meal", category: "microwavesAndToasterOvens", pics: ["../media/img/categoryKitchen/microwavesAndToasterOvens/61a.jpg", "../media/img/categoryKitchen/microwavesAndToasterOvens/61b.jpg"] },
    { id: 62, name: "SAUTER", price: 499, description: "For a Hot Meal", category: "microwavesAndToasterOvens", pics: ["../media/img/categoryKitchen/microwavesAndToasterOvens/62a.jpg", "../media/img/categoryKitchen/microwavesAndToasterOvens/62b.jpg"] },
    { id: 63, name: "SAMSUNG", price: 399, description: "For a Hot Meal", category: "microwavesAndToasterOvens", pics: ["../media/img/categoryKitchen/microwavesAndToasterOvens/63a.jpg", "../media/img/categoryKitchen/microwavesAndToasterOvens/63b.jpg"] },
    { id: 64, name: "SAMSUNG", price: 299, description: "For a Hot Meal", category: "microwavesAndToasterOvens", pics: ["../media/img/categoryKitchen/microwavesAndToasterOvens/64a.jpg", "../media/img/categoryKitchen/microwavesAndToasterOvens/64b.jpg"] },
    { id: 65, name: "SAUTER", price: 359, description: "For a Hot Meal", category: "microwavesAndToasterOvens", pics: ["../media/img/categoryKitchen/microwavesAndToasterOvens/65a.jpg", "../media/img/categoryKitchen/microwavesAndToasterOvens/65b.jpg"] },
    { id: 66, name: "MORPHY RICHARDS", price: 299, description: "For a Crispy Toast", category: "toasters", pics: ["../media/img/categoryKitchen/toasters/66a.jpg", "../media/img/categoryKitchen/toasters/66b.jpg"] },
    { id: 67, name: "PHILIPS", price: 399, description: "For a Crispy Toast", category: "toasters", pics: ["../media/img/categoryKitchen/toasters/67a.jpg", "../media/img/categoryKitchen/toasters/67b.jpg"] },
    { id: 68, name: "SAUTER", price: 249, description: "For a Crispy Toast", category: "toasters", pics: ["../media/img/categoryKitchen/toasters/68a.jpg", "../media/img/categoryKitchen/toasters/68b.jpg"] },
    { id: 69, name: "PHILIPS", price: 299, description: "For a Crispy Toast", category: "toasters", pics: ["../media/img/categoryKitchen/toasters/69a.jpg", "../media/img/categoryKitchen/toasters/69b.jpg"] },
    { id: 70, name: "BREVILLE", price: 279, description: "For a Crispy Toast", category: "toasters", pics: ["../media/img/categoryKitchen/toasters/70a.jpeg", "../media/img/categoryKitchen/toasters/70b.jpeg"] },
    { id: 71, name: "SHARP", price: 399, description: "Best Mixing", category: "mixers", pics: ["../media/img/categoryKitchen/mixers/71a.png", "../media/img/categoryKitchen/mixers/71b.png"] },
    { id: 72, name: "SAMSUNG", price: 499, description: "Best Mixing", category: "mixers", pics: ["../media/img/categoryKitchen/mixers/72a.jpg", "../media/img/categoryKitchen/mixers/72b.jpg"] },
    { id: 73, name: "SAUTER", price: 399, description: "Best Mixing", category: "mixers", pics: ["../media/img/categoryKitchen/mixers/73a.jpg", "../media/img/categoryKitchen/mixers/73b.jpg"] },
    { id: 74, name: "PHILIPS", price: 389, description: "Best Mixing", category: "mixers", pics: ["../media/img/categoryKitchen/mixers/74a.jpg", "../media/img/categoryKitchen/mixers/74b.jpg"] },
    { id: 75, name: "SONY", price: 349, description: "Best Mixing", category: "mixers", pics: ["../media/img/categoryKitchen/mixers/75a.jpg", "../media/img/categoryKitchen/mixers/75b.jpg"] },
    { id: 76, name: "SAUTER", price: 99, description: "Strong and Compact", category: "electricStoves", pics: ["../media/img/categoryKitchen/electricStoves/76a.jpg", "../media/img/categoryKitchen/electricStoves/76b.jpg"] },
    { id: 77, name: "SONY", price: 199, description: "Strong and Compact", category: "electricStoves", pics: ["../media/img/categoryKitchen/electricStoves/77a.jpg", "../media/img/categoryKitchen/electricStoves/77b.jpg"] },
    { id: 78, name: "SAUTER", price: 129, description: "Strong and Compact", category: "electricStoves", pics: ["../media/img/categoryKitchen/electricStoves/78a.jpg", "../media/img/categoryKitchen/electricStoves/78b.jpg"] },
    { id: 79, name: "SONY", price: 179, description: "Strong and Compact", category: "electricStoves", pics: ["../media/img/categoryKitchen/electricStoves/79a.jpg", "../media/img/categoryKitchen/electricStoves/79b.jpg"] },
    { id: 80, name: "GOLD LINE", price: 189, description: "Strong and Compact", category: "electricStoves", pics: ["../media/img/categoryKitchen/electricStoves/80a.jpg", "../media/img/categoryKitchen/electricStoves/80b.jpg"] }
];



var cartCounter = document.getElementById("cartCounter");

cartCounter.innerText = 3;
